baseURL: https://juan-aranguren.netlify.app/
languageCode: en-us
title: Portfolio website for Juan Aranguren
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my personal website where you will have the time of your life
#     AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Juan Aranguren
  blog: {}
  contact:
    address:
      - city: London, NW1 6DP
        country: United Kingdom
        street: 23 Radley House
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jaranguren.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 078-421939197
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/juan.aranguren.56/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/juanarangurenn/
      - icon: fa-github
        label: GitHub
        url: https://github.com/juanaranguren1995/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/juan-aranguren-8b743413b/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: This is my university, where I am studying my MBA
        title: Welcome to LBS
        url: blogs/LBS2
      - image: Kitesurf.jpg
        subtitle: I have started kitesurfing in 2020 and I love it
        title: My last passion
        url: blogs/tempus
      - image: Familia.jpg
        subtitle: Yes, as you can see we are many
        title: Meet my HUGE family
        url: blogs/magna
      - image: Mass Shootings.jpg
        subtitle: Let's epxlore the mass shootings
        title: Let's now get serious and explore my work in Data Analysis in R
        url: blogs/Mass_Shootings
      - image: CreditFraud.jpg
        subtitle: Let's explore a credit card fraud analysis
        title: Credit Card Fraud
        url: blogs/Card_Fraud
      - image: Stock.jpg
        subtitle: Let's explore a risk return analysis and its code
        title: Risk Return of DJIA Stocks
        url: blogs/risk_return
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs

markup:
  goldmark:
    renderer:
      unsafe: true
